# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'motion_control.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(720, 221)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.dockWidgetContents)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 581, 179))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.groups_layout = QtGui.QHBoxLayout()
        self.groups_layout.setObjectName(_fromUtf8("groups_layout"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btn_camera_right = QtGui.QPushButton(self.groupBox)
        self.btn_camera_right.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_camera_right.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/move_right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_camera_right.setIcon(icon)
        self.btn_camera_right.setAutoRepeat(True)
        self.btn_camera_right.setAutoRepeatDelay(50)
        self.btn_camera_right.setAutoRepeatInterval(50)
        self.btn_camera_right.setObjectName(_fromUtf8("btn_camera_right"))
        self.gridLayout.addWidget(self.btn_camera_right, 1, 2, 1, 1)
        self.btn_camera_left = QtGui.QPushButton(self.groupBox)
        self.btn_camera_left.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_camera_left.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/move_left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_camera_left.setIcon(icon1)
        self.btn_camera_left.setAutoRepeat(True)
        self.btn_camera_left.setAutoRepeatDelay(50)
        self.btn_camera_left.setAutoRepeatInterval(50)
        self.btn_camera_left.setObjectName(_fromUtf8("btn_camera_left"))
        self.gridLayout.addWidget(self.btn_camera_left, 1, 0, 1, 1)
        self.btn_camera_backward = QtGui.QPushButton(self.groupBox)
        self.btn_camera_backward.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_camera_backward.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/move_backward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_camera_backward.setIcon(icon2)
        self.btn_camera_backward.setAutoRepeat(True)
        self.btn_camera_backward.setAutoRepeatDelay(50)
        self.btn_camera_backward.setAutoRepeatInterval(50)
        self.btn_camera_backward.setObjectName(_fromUtf8("btn_camera_backward"))
        self.gridLayout.addWidget(self.btn_camera_backward, 1, 1, 1, 1)
        self.btn_camera_up = QtGui.QPushButton(self.groupBox)
        self.btn_camera_up.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_camera_up.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/move_up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_camera_up.setIcon(icon3)
        self.btn_camera_up.setAutoRepeat(True)
        self.btn_camera_up.setAutoRepeatDelay(50)
        self.btn_camera_up.setAutoRepeatInterval(50)
        self.btn_camera_up.setObjectName(_fromUtf8("btn_camera_up"))
        self.gridLayout.addWidget(self.btn_camera_up, 0, 2, 1, 1)
        self.btn_camera_forward = QtGui.QPushButton(self.groupBox)
        self.btn_camera_forward.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_camera_forward.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/move_forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_camera_forward.setIcon(icon4)
        self.btn_camera_forward.setAutoRepeat(True)
        self.btn_camera_forward.setAutoRepeatDelay(50)
        self.btn_camera_forward.setAutoRepeatInterval(50)
        self.btn_camera_forward.setObjectName(_fromUtf8("btn_camera_forward"))
        self.gridLayout.addWidget(self.btn_camera_forward, 0, 1, 1, 1)
        self.btn_camera_down = QtGui.QPushButton(self.groupBox)
        self.btn_camera_down.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_camera_down.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/move_down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_camera_down.setIcon(icon5)
        self.btn_camera_down.setAutoRepeat(True)
        self.btn_camera_down.setAutoRepeatDelay(50)
        self.btn_camera_down.setAutoRepeatInterval(50)
        self.btn_camera_down.setObjectName(_fromUtf8("btn_camera_down"))
        self.gridLayout.addWidget(self.btn_camera_down, 0, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.groups_layout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btn_camera_rotate_left = QtGui.QPushButton(self.groupBox_2)
        self.btn_camera_rotate_left.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_camera_rotate_left.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/rotate_left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_camera_rotate_left.setIcon(icon6)
        self.btn_camera_rotate_left.setAutoRepeat(True)
        self.btn_camera_rotate_left.setAutoRepeatDelay(50)
        self.btn_camera_rotate_left.setAutoRepeatInterval(50)
        self.btn_camera_rotate_left.setObjectName(_fromUtf8("btn_camera_rotate_left"))
        self.gridLayout_3.addWidget(self.btn_camera_rotate_left, 1, 0, 1, 1)
        self.btn_camera_rotate_right = QtGui.QPushButton(self.groupBox_2)
        self.btn_camera_rotate_right.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_camera_rotate_right.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/rotate_right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_camera_rotate_right.setIcon(icon7)
        self.btn_camera_rotate_right.setAutoRepeat(True)
        self.btn_camera_rotate_right.setAutoRepeatDelay(50)
        self.btn_camera_rotate_right.setAutoRepeatInterval(50)
        self.btn_camera_rotate_right.setObjectName(_fromUtf8("btn_camera_rotate_right"))
        self.gridLayout_3.addWidget(self.btn_camera_rotate_right, 1, 2, 1, 1)
        self.btn_camera_rotate_down = QtGui.QPushButton(self.groupBox_2)
        self.btn_camera_rotate_down.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_camera_rotate_down.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/rotate_down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_camera_rotate_down.setIcon(icon8)
        self.btn_camera_rotate_down.setAutoRepeat(True)
        self.btn_camera_rotate_down.setAutoRepeatDelay(50)
        self.btn_camera_rotate_down.setAutoRepeatInterval(50)
        self.btn_camera_rotate_down.setObjectName(_fromUtf8("btn_camera_rotate_down"))
        self.gridLayout_3.addWidget(self.btn_camera_rotate_down, 1, 1, 1, 1)
        self.btn_camera_rotate_up = QtGui.QPushButton(self.groupBox_2)
        self.btn_camera_rotate_up.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_camera_rotate_up.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/rotate_up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_camera_rotate_up.setIcon(icon9)
        self.btn_camera_rotate_up.setAutoRepeat(True)
        self.btn_camera_rotate_up.setAutoRepeatDelay(50)
        self.btn_camera_rotate_up.setAutoRepeatInterval(50)
        self.btn_camera_rotate_up.setObjectName(_fromUtf8("btn_camera_rotate_up"))
        self.gridLayout_3.addWidget(self.btn_camera_rotate_up, 0, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.groups_layout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.btn_item_x_up = QtGui.QPushButton(self.groupBox_3)
        self.btn_item_x_up.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_item_x_up.setText(_fromUtf8(""))
        self.btn_item_x_up.setIcon(icon4)
        self.btn_item_x_up.setAutoRepeat(True)
        self.btn_item_x_up.setAutoRepeatDelay(50)
        self.btn_item_x_up.setAutoRepeatInterval(50)
        self.btn_item_x_up.setObjectName(_fromUtf8("btn_item_x_up"))
        self.gridLayout_5.addWidget(self.btn_item_x_up, 0, 1, 1, 1)
        self.btn_item_x_down = QtGui.QPushButton(self.groupBox_3)
        self.btn_item_x_down.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_item_x_down.setText(_fromUtf8(""))
        self.btn_item_x_down.setIcon(icon2)
        self.btn_item_x_down.setAutoRepeat(True)
        self.btn_item_x_down.setAutoRepeatDelay(50)
        self.btn_item_x_down.setAutoRepeatInterval(50)
        self.btn_item_x_down.setObjectName(_fromUtf8("btn_item_x_down"))
        self.gridLayout_5.addWidget(self.btn_item_x_down, 1, 1, 1, 1)
        self.btn_item_z_up = QtGui.QPushButton(self.groupBox_3)
        self.btn_item_z_up.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_item_z_up.setText(_fromUtf8(""))
        self.btn_item_z_up.setIcon(icon3)
        self.btn_item_z_up.setAutoRepeat(True)
        self.btn_item_z_up.setAutoRepeatDelay(50)
        self.btn_item_z_up.setAutoRepeatInterval(50)
        self.btn_item_z_up.setObjectName(_fromUtf8("btn_item_z_up"))
        self.gridLayout_5.addWidget(self.btn_item_z_up, 0, 2, 1, 1)
        self.btn_item_y_up = QtGui.QPushButton(self.groupBox_3)
        self.btn_item_y_up.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_item_y_up.setText(_fromUtf8(""))
        self.btn_item_y_up.setIcon(icon)
        self.btn_item_y_up.setAutoRepeat(True)
        self.btn_item_y_up.setAutoRepeatDelay(50)
        self.btn_item_y_up.setAutoRepeatInterval(50)
        self.btn_item_y_up.setObjectName(_fromUtf8("btn_item_y_up"))
        self.gridLayout_5.addWidget(self.btn_item_y_up, 1, 2, 1, 1)
        self.btn_item_y_down = QtGui.QPushButton(self.groupBox_3)
        self.btn_item_y_down.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_item_y_down.setText(_fromUtf8(""))
        self.btn_item_y_down.setIcon(icon1)
        self.btn_item_y_down.setAutoRepeat(True)
        self.btn_item_y_down.setAutoRepeatDelay(50)
        self.btn_item_y_down.setAutoRepeatInterval(50)
        self.btn_item_y_down.setObjectName(_fromUtf8("btn_item_y_down"))
        self.gridLayout_5.addWidget(self.btn_item_y_down, 1, 0, 1, 1)
        self.btn_item_z_down = QtGui.QPushButton(self.groupBox_3)
        self.btn_item_z_down.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_item_z_down.setText(_fromUtf8(""))
        self.btn_item_z_down.setIcon(icon5)
        self.btn_item_z_down.setAutoRepeat(True)
        self.btn_item_z_down.setAutoRepeatDelay(50)
        self.btn_item_z_down.setAutoRepeatInterval(50)
        self.btn_item_z_down.setObjectName(_fromUtf8("btn_item_z_down"))
        self.gridLayout_5.addWidget(self.btn_item_z_down, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_5)
        self.groups_layout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.btn_item_rotate_counter_clockwise = QtGui.QPushButton(self.groupBox_4)
        self.btn_item_rotate_counter_clockwise.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_item_rotate_counter_clockwise.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/spin_left.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_item_rotate_counter_clockwise.setIcon(icon10)
        self.btn_item_rotate_counter_clockwise.setAutoRepeat(True)
        self.btn_item_rotate_counter_clockwise.setAutoRepeatDelay(50)
        self.btn_item_rotate_counter_clockwise.setAutoRepeatInterval(50)
        self.btn_item_rotate_counter_clockwise.setObjectName(_fromUtf8("btn_item_rotate_counter_clockwise"))
        self.gridLayout_6.addWidget(self.btn_item_rotate_counter_clockwise, 0, 1, 1, 1)
        self.btn_item_rotate_clockwise = QtGui.QPushButton(self.groupBox_4)
        self.btn_item_rotate_clockwise.setStyleSheet(_fromUtf8("image: url(:/icon/move_backward.png);"))
        self.btn_item_rotate_clockwise.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/spin_right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_item_rotate_clockwise.setIcon(icon11)
        self.btn_item_rotate_clockwise.setAutoRepeat(True)
        self.btn_item_rotate_clockwise.setAutoRepeatDelay(50)
        self.btn_item_rotate_clockwise.setAutoRepeatInterval(50)
        self.btn_item_rotate_clockwise.setObjectName(_fromUtf8("btn_item_rotate_clockwise"))
        self.gridLayout_6.addWidget(self.btn_item_rotate_clockwise, 0, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_6)
        self.groups_layout.addWidget(self.groupBox_4)
        self.horizontalLayout_6.addLayout(self.groups_layout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setToolTip(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setToolTip(_translate("DockWidget", "icons Designed by Freepik and distributed by Flaticon", None))
        DockWidget.setWindowTitle(_translate("DockWidget", "DockWidget", None))
        self.groupBox.setTitle(_translate("DockWidget", "Move Camera", None))
        self.btn_camera_right.setToolTip(_translate("DockWidget", "right", None))
        self.btn_camera_left.setToolTip(_translate("DockWidget", "left", None))
        self.btn_camera_backward.setToolTip(_translate("DockWidget", "backward", None))
        self.btn_camera_up.setToolTip(_translate("DockWidget", "up", None))
        self.btn_camera_forward.setToolTip(_translate("DockWidget", "foreward", None))
        self.btn_camera_down.setToolTip(_translate("DockWidget", "down", None))
        self.groupBox_2.setTitle(_translate("DockWidget", "Rotate Camera", None))
        self.groupBox_3.setTitle(_translate("DockWidget", "Move Item", None))
        self.groupBox_4.setTitle(_translate("DockWidget", "Rotate Item", None))
        self.label.setText(_translate("DockWidget", "icons were Designed by \n"
"Freepik and distributed\n"
" by Flaticon", None))

from icons import icons_rc
